export const getCommentSyntax = (extension: string): string => {
  const syntaxMap: { [key: string]: string } = {
    js: "//",
    ts: "//",
    py: "#",
    java: "//",
    cpp: "//",
    c: "//",
    cs: "//",
    rb: "#",
    php: "//",
    html: "<!-- -->",
    css: "/* */",
    xml: "<!-- -->",
    sh: "#",
    go: "//",
    rs: "//",
    swift: "//",
    kt: "//",
    scala: "//",
    lua: "--",
    sql: "--",
    r: "#",
    pl: "#",
    hs: "--",
    ml: "(* *)",
    clj: ";;",
    cljs: ";;",
    edn: ";;",
    erl: "%",
    ex: "#",
    exs: "#",
    dart: "//",
    vb: "'",
    vbs: "'",
    ps1: "#",
    yaml: "#",
    yml: "#",
    toml: "#",
    ini: ";",
    bat: "REM",
    cmd: "REM",
  };

  return syntaxMap[extension] || "//";
};
